{
 "title": "kubernetes-服务",
 "description": "kubernetes-服务",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "命名空间", "query": "label_values(namespace)" },
   {
    "name": "Deployment",
    "label": "应用名",
    "query": "label_values(kube_deployment_labels{namespace=~\"^$Namespace.*$\"},deployment)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"^$Namespace.*$\", pod_name=~\"^$Deployment.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"^$Namespace.*$\",pod_name=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{namespace=~\"^$Namespace.*$\",deployment=~\".*$Deployment\"}) or vector(0)) + (sum(kube_statefulset_replicas{namespace=~\"^$Namespace.*$\",statefulset=~\".*$Deployment\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{namespace=~\"^$Namespace.*$\",daemonset=~\".*$Deployment\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{namespace=~\"^$Namespace.*$\",deployment=~\".*$Deployment\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{namespace=~\"^$Namespace.*$\",statefulset=~\".*$Deployment\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{namespace=~\"^$Namespace.*$\",daemonset=~\".*$Deployment\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{namespace=~\"^$Namespace.*$\",deployment=~\".*$Deployment\"}) or vector(0)) + (sum(kube_statefulset_replicas{namespace=~\"^$Namespace.*$\",statefulset=~\".*$Deployment\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{namespace=~\"^$Namespace.*$\",daemonset=~\".*$Deployment\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"^$Namespace.*$\",pod_name=~\"^$Deployment.*$\"}[2m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"^$Namespace.*$\",pod_name=~\"^$Deployment.*$\", pod_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{namespace=~\"^$Namespace.*$\",deployment=~\".*$Deployment\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{namespace=~\"^$Namespace.*$\",statefulset=~\".*$Deployment\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{namespace=~\"^$Namespace.*$\",daemonset=~\".*$Deployment\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{namespace=~\"^$Namespace.*$\",deployment=~\".*$Deployment\"}) or vector(0)) + (sum(kube_statefulset_replicas{namespace=~\"^$Namespace.*$\",statefulset=~\".*$Deployment\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{namespace=~\"^$Namespace.*$\",daemonset=~\".*$Deployment\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "内存使用率",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=~\"^$Namespace.*$\",id!=\"/\",container!~\"POD|ilogtail|logtail|\",container=~\"^$Deployment.*$\"}) by (namespace,pod) /avg(kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$Namespace.*$\",id!=\"/\",container!~\"POD|ilogtail|logtail|\",container=~\"^$Deployment.*$\"}) by (namespace,pod) ",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"^$Namespace.*$\",id!=\"/\",pod_name=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"^$Namespace.*$\",image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\",}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} "
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"^$Namespace.*$\",id!=\"/\",pod_name=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{namespace=~\"^$Namespace.*$\",id!=\"/\",pod_name=~\"^$Deployment.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}