rules:
  endpoint_relation_resp_time_rule:
    metrics-name: endpoint_relation_resp_time
    threshold: 10000
    op: ">"
    period: 10
    count: 2
    message: 接口响应时间超过10秒({name})

webhooks:
  - http://192.168.2.20:8060/dingtalk/webhook1/send

