rules:
  endpoint_relation_resp_time_rule:
    metrics-name: endpoint_relation_resp_time
    threshold: 5000
    op: ">"
    period: 10
    count: 2
    message: 接口超时10秒  {name}
  endpoint_relation_error_resp_time_rule:
    metrics-name: endpoint_relation_error_resp_time
    threshold: 1
    op: ">"
    period: 10
    count: 2
    message: 接口报错  {name} {responseCode}
webhooks:
  - http://192.168.2.20:8060/dingtalk/webhook1/send

