version: "3.8"

networks:
  loki:

services:

  loki-1:
    image: grafana/loki:2.1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/loki/
      - ./chunks:/loki/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: always

  loki-2:
    image: grafana/loki:2.1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/loki/
      - ./chunks:/loki/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: always

  loki-3:
    image: grafana/loki:2.1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/loki/
      - ./chunks:/loki/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - loki
    restart: always

  loki-frontend:
    image: grafana/loki:2.1.0
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./config:/etc/loki/
    ports:
        - "3100"
    command: "-config.file=/etc/loki/loki-docker-memberlist-boltdb-shipper.yaml -target=query-frontend"
    networks:
      - loki
    deploy:
      mode: replicated
      replicas: 2
    restart: always

  loki-gateway:
    image: nginx:1.19
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx-loki-gateway.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
      - "3100:3100"
    networks:
      - loki
    restart: always
    depends_on:
      - loki-1
      - loki-2
      - loki-3

  promtail:
    image: grafana/promtail:2.1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail-gateway.yaml -config.expand-env=true
    networks:
      - loki
    restart: always
    depends_on:
      - loki-gateway