apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  namespace: namespace_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      containers:
      - args:
          - -config.file=/etc/promtail/promtail-config.yaml
          - -config.expand-env=true
        name: promtail
        image: grafana/promtail:2.1.0
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVICE_NAME
            value: service_name
        resources:
          limits:
            cpu: 1
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
        volumeMounts:
          - mountPath: /etc/localtime
            name: date-config
          - mountPath: /mnt
            name: logs-dir
          - mountPath: /etc/promtail/promtail-config.yaml
            name: promtail-config
            readOnly: true
            subPath: promtail-config.yaml
      - env:
          - name: restart
            value: restart_pod
          - name: mxjvm
            value: service_max_jvm
          - name: msjvm
            value: service_min_jvm
        name: service_name
        image: service_image
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 60
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: service_memM
          requests:
            cpu: 250m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /data/servicesLog/logs
            name: logs-dir
          - mountPath: /etc/localtime
            name: date-config
      nodeSelector:
        dev: dev
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: date-config
      - emptyDir: {}
        name: logs-dir
      - configMap:
          name: promtail-config
        name: promtail-config